name: sms_autofill
description: Flutter plugin to provide SMS code autofill support
version: 1.3.1
homepage: https://github.com/jaumard/sms_autofill

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  pin_input_text_field:
    git:
      url: https://github.com/NaderRaida/pin_input_text_field_clone.git
      ref: 1.0.0

  flutter:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.jaumard.smsautofill
        pluginClass: SmsAutoFillPlugin
      ios:
        pluginClass: SmsAutoFillPlugin
